AllCops:
    NewCops: enable

Style/Documentation:
  Description: "Document classes and non-namespace modules."
  Enabled: false

Layout/LineLength:
  Description: "Limit lines to 100 characters. (Default is 80)"
  Max: 100

Metrics/MethodLength:
  Description: "Method Lenght"
  Max: 200

Metrics/ClassLength:
  Description: "Class Lenght"
  Max: 800

Style/FrozenStringLiteralComment:
  Description: To help transition from Ruby 2.3.0 to Ruby 3.0.
  Enabled: false
