plugins:
  - solargraph-rails

include:
- "**/*.rb"

exclude:
- spec/**/*
- test/**/*
- vendor/**/*
- ".bundle/**/*"

require: []

domains: []

reporters:
- rubocop
- require_not_found
- typecheck

formatter:
  rubocop:

max_files: 5000
