live_config_reload = true

[font]
size = 14

[window]
title = "Terminal"
padding = { x = 2, y = 2 }
opacity = 0.95
dimensions = { columns = 100, lines = 30 }

[selection]
save_to_clipboard =  true

[cursor]
style = { shape = "Block", blinking = "On" }

[colors.primary]
background = '#1a1b26'
foreground = '#a9b1d6'

[colors.normal]
black   = '#32344a'
red     = '#f7768e'
green   = '#9ece6a'
yellow  = '#e0af68'
blue    = '#7aa2f7'
magenta = '#ad8ee6'
cyan    = '#449dab'
white   = '#787c99'

[colors.bright]
black   = '#444b6a'
red     = '#ff7a93'
green   = '#b9f27c'
yellow  = '#ff9e64'
blue    = '#7da6ff'
magenta = '#bb9af7'
cyan    = '#0db9d7'
white   = '#acb0d0'
